# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'

require "capistrano/bundler"
require 'capistrano/rails/assets'
require 'capistrano/rails/migrations'
require 'capistrano/delayed_job'
require 'capistrano/rbenv'

require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
