- name: Create database
  become: true
  become_user: postgres
  postgresql_db: name={{ database_name }}
                 encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template0' state=present

- name: Create database user
  become: true
  become_user: postgres
  postgresql_user: db={{ database_name }} name={{ database_username }} password={{ database_password }} role_attr_flags=CREATEDB,SUPERUSER
