---

- name: Enable and start firewalld
  service: name=firewalld
           enabled=yes
           state=started

- name: Open ssh port in firewall
  firewalld: service=ssh permanent=true state=enabled
  notify: Restart firewalld
